### PR TITLE
Tweaked the regex string for the kill command so that it only picks up the run command

### PR DESCRIPTION
**Pull request by gunslingerfry**

### CODE REVIEW

**Comment by autolyticus** [comment]
Hi @gunslingerfry, and thanks for contributing!

A couple of things, 

This project enforces the DCO so you need to add the Signed off by line at the end of the commit message for your code to be accepted. Please refer this [link](https://github.com/probot/dco) for more information.

Your commit message mentions the '-x' flag but it hasn't been implemented in the PR. 
And from what I know about regex, [f]lutter isn't any different from flutter. But I might be wrong so feel free to correct me on that.

Cheers

**Comment by gunslingerfry** [comment]
@reisub0 Thanks, I'll look at the DCO. There isn't a mention of a -x flag, I think that is just the description getting cut off at 'rege...'

Regarding the character class, the grep command is notorious for finding itself when applied to ps. The character class makes the pgrep command look like `pgrep [f]lutter_tool.*run` which will not match with itself (because of the brackets for the character class). 

Maybe it would help to describe the problem that it is fixing: Initially the plugin didn't work on my machine because it matched 3 pids. When testing the command at a terminal it also matched my `flutter analyze --watch` command I had in another terminal. After shutting that down, it still pulled up 2 pids but the same command at the terminal only showed 1. 

Now that I think about it, it probably _isn't_ the pgrep process that is matching. I bet _it's the shell that vim creates_. I will check that when I get home because it's worth knowing.

**Comment by autolyticus** [comment]
@gunslingerfry Silly me, reading that x as a command line flag. 

Ah, that's interesting. I get the rationale for the seemingly unnecessary character class, to prevent it from matching itself.
Could you please tell me more about the system you're working on? Because as far as I know `kill` sends SIGUSR1 to all the processes that match the regex.

With some quick testing, almost any regex starting with flutter tool I try does work for my case on my Arch Linux machine.

I do however agree that it's better to be more selective and only affect the exact process that's ending with a `run`. So it's definitely better to have a stricter regex.

**Comment by gunslingerfry** [comment]
Sorry for the delay, just getting back to learning flutter :)
I am running:
Ubuntu 18.04
vim 8.0.1453
bash 4.4.19(1)

So I was actually right and wrong. It is not picking up the vim shell process. It is picking up the pgrep process _and_ the subshell it creates (the `$(command)`) for a total of 4. I tested this by changing the command to `silent execute '!echo $(pgrep -f flutter_tool -a) > $PWD/processes.txt'`. Here's the output, adding newlines:
```
11362 /home/matthew/flutter/bin/cache/dart-sdk/bin/dart /home/matthew/flutter/bin/cache/flutter_tools.snapshot analyze --watch
12871 /home/matthew/flutter/bin/cache/dart-sdk/bin/dart /home/matthew/flutter/bin/cache/flutter_tools.snapshot run
20999 /bin/bash -c echo $(pgrep -f flutter_tool -a) > $PWD/processes.txt
21000 /bin/bash -c echo $(pgrep -f flutter_tool -a) > $PWD/processes.txt
```

**Comment by gunslingerfry** [comment]
Alright, I committed with the wrong sign-off e-mail then re-pushed with the right sign-off e-mail. Not sure if I did it right...

**Comment by autolyticus** [comment]
@gunslingerfry Wow, I wouldn't have expected that 4 processes would show up. Especially alarming considering that the default action on receiving a SIGUSR1 is to terminate the process. So I would hazard a guess that it was killing its own subshell or something, causing it to fail.

Thank you for helping to make hot-reload better

Cheers! :beers:

**Pull request merged**
